eureka:
  instance:
    hostname: discovery-service
  client:
    serviceUrl:
      defaultZone: http://discovery-service:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,prometheus
  endpoint:
    health:
      show-details: always

spring:
  cloud:
    config:
      override-system-properties: false