server:
  port: 8090

spring:
  data:
    mongodb:
      host: localhost
      port: 27017
      database: customer-db
      username: arnold
      password: arnold_password
      authentication-database: admin

# CONFIGURATIONS ACTUATOR
management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      customerCB:
        registerHealthIndicator: true
        eventConsumerBufferSize: 10
        automaticTransitionFromOpenToHalfOpenEnabled: true
        slidingWindowSize: 10
        slidingWindowType: COUNT_BASED
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 5s
        permittedNumberOfCallsInHalfOpenState: 3
        failureRateThreshold: 50
  retry:
    instances:
      customerCB:
        registerHealthIndicator: true
        maxRetryAttempts: 5
        waitDuration: 10s
  rateLimiter:
    instances:
      customerCB:
        registerHealthIndicator: true
        limitForPeriod: 5
        limitRefreshPeriod: 10s
        timeoutDuration: 3s