spring:
    application:
        name: config-server
    profiles:
        active:
            - native
    cloud:
        config:
            server:
                native:
                    search-locations:
                        - classpath:/configurations
management:
  endpoints:
    web:
      exposure:
        include: health,info

server:
    port: 8888